services:
  test-db:
    image: postgres:15-alpine
    container_name: pdx-diy-test-db
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432" # Use port 5433 to avoid conflicts with local PostgreSQL
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

volumes:
  test-db-data:

networks:
  test-network:
    driver: bridge
